# Lint only these paths
included:
  - Kuna
  - KunaWidget

# Common folders to ignore
excluded:
  - Carthage
  - Pods
  - DerivedData
  - Scripts
  - .build

# Make output show inline in GitHub checks
reporter: github-actions-logging

# Turn off a couple of noisy rules (adjust to taste)
disabled_rules:
  - trailing_whitespace
  - identifier_name
  - multiple_closures_with_trailing_closure

# Turn on stricter rules that catch AI slip-ups
opt_in_rules:
  - force_unwrapping
  - force_cast
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - nesting
  - redundant_optional_initialization
  - unused_declaration
  - empty_count
  - explicit_self
  - yoda_condition
  - fatal_error_message
  - discouraged_direct_init
  - todo

# Reasonable thresholds
line_length: 130

identifier_name:
  excluded:
    - id
    - x
    - y
    - i
    - j

empty_count:
  severity: warning

type_body_length:
  warning: 600   # only warn above 600, no error

file_length:
  warning: 900   # only warn above 900, no error

function_body_length:
  warning: 100   # only warn above 100, no error

cyclomatic_complexity:
  warning: 18    # only warn above 18, no error

force_cast:
  severity: warning

# ---- Custom rules ----
custom_rules:
  no_hardcoded_ui_strings:
    included: ".*\\.swift"
    name: "No hardcoded UI strings"
    message: "Localize user-visible strings (use String(localized:), LocalizedStringKey, or NSLocalizedString). Add // noloc to intentionally skip."
    severity: error
    regex: |
      (?x)
      # 1) Initializers that commonly take user-facing titles/labels
      (?:
        \b
        (?:SwiftUI\.)?
        (Text|Button|Label|Toggle|Section|Menu|Picker|TextField|SecureField)
        \s* \(
        \s* "
      )
      |
      # 2) Common SwiftUI modifiers with string titles
      (?:
        \.
        (navigationTitle|navigationBarTitle|alert|confirmationDialog|tabItem|accessibilityLabel|accessibilityHint)
        \s* \(
        \s* "
      )
    excluded_regex: |
      (?x)
      (String\s*\(\s*localized:) |
      (NSLocalizedString\s*\()   |
      (LocalizedStringKey\s*\()  |
      (//\s*noloc\b)

  no_print_statements:
    included: ".*\\.swift"
    name: "No print statements"
    message: "Remove print() calls. Use os_log, Logger, or your logging framework instead. Add // print-ok to allow intentionally."
    severity: error
    regex: |
      (?x)\bprint\s*\(
    excluded_regex: |
      (?x)(//\s*print-ok\b)
