# Lint only these paths
included:
  - Kuna
  - KunaWidget

# Common folders to ignore
excluded:
  - Carthage
  - Pods
  - DerivedData
  - Scripts
  - .build

# Make output show inline in GitHub checks
reporter: github-actions-logging

# Turn off a couple of noisy rules (adjust to taste)
disabled_rules:
  - trailing_whitespace
  - identifier_name
  - multiple_closures_with_trailing_closure

# Turn on stricter rules that catch AI slip-ups
opt_in_rules:
  - force_unwrapping
  - force_cast
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - nesting
  - redundant_optional_initialization
  - unused_declaration
  - empty_count
  - explicit_self
  - yoda_condition
  - fatal_error_message
  - discouraged_direct_init
  - todo

# Reasonable thresholds
line_length: 130

identifier_name:
  excluded: [id, x, y, i, j]

empty_count:
  severity: warning

type_body_length:
  warning: 600

file_length:
  warning: 900

function_body_length:
  warning: 100

cyclomatic_complexity:
  warning: 18

force_cast:
  severity: warning

# ---- Custom rules ----
custom_rules:
  no_print_statements:
    included: ".*\\.swift"
    name: "No print statements"
    message: "Remove print() calls. Use os_log, Logger, or your logging framework instead. Add // print-ok to allow intentionally."
    severity: error
    regex: "\\bprint\\s*\\("
    excluded_regex: "//\\s*print-ok"

  # (optional) also block debugPrint/dump
  no_debug_prints:
    included: ".*\\.swift"
    name: "No debug prints"
    message: "Remove debugPrint()/dump(). Add // print-ok only if intentional."
    severity: error
    regex: "\\b(?:debugPrint|dump)\\s*\\("
    excluded_regex: "//\\s*print-ok"
