project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /Kuna/Resources/Localizable.xcstrings
    translation: /Kuna/Resources/Localizable.%two_letters_code%.xcstrings
