---
name: 💡 Feature request
description: Suggest an idea for Kuna
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
    label: Problem
    description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
    label: Proposed solution
    description: Describe what you’d like to happen.
  - type: textarea
    id: alternatives
    attributes:
    label: Alternatives
    description: Any alternative solutions you’ve considered?
  - type: textarea
    id: context
    attributes:
    label: Additional context
    description: Add any other context or screenshots.