opt_out_usage
default_platform(:ios)

platform :ios do
  lane :tests do
    devices_env = ENV["DEVICES"]
    devices = devices_env ? devices_env.split(",").map(&:strip) : ["iPhone 16"]

    scan(
      scheme: "Kuna",
      project: "Kuna.xcodeproj",
      devices: devices,
      clean: true,
      result_bundle: true,
      code_coverage: true,
      testplan: "UnitTestPlan",
      output_types: "junit",
      output_directory: "fastlane/test_output",
      output_files: "junit.xml",
      skip_testing: ["KunaEventKitTests"]
    )
  end

  lane :ci_tests do
    devices_env = ENV["DEVICES"]
    devices = devices_env ? devices_env.split(",").map(&:strip) : ["iPhone 16"]

    scan(
      scheme: "Kuna",
      project: "Kuna.xcodeproj",
      devices: devices,
      clean: true,
      result_bundle: true,
      code_coverage: true,
      testplan: "UnitTestPlan",
      output_types: "junit,json",
      output_directory: "fastlane/test_output",
      output_files: "junit.xml,test_result.json",
      skip_testing: ["KunaEventKitTests"],
      fail_build: true,
      xcargs: "-allowProvisioningUpdates"
    )

    xcov(
      project: "Kuna.xcodeproj",
      scheme: "Kuna",
      output_directory: "fastlane/test_output",
      minimum_coverage_percentage: 0.0
    )
  end

  lane :build_ipa do
    ensure_git_status_clean

    match(
      type: "appstore",
      readonly: true,
      git_url: ENV["MATCH_GIT_URL"],
      git_branch: ENV["MATCH_GIT_BRANCH"],
      keychain_name: "build.keychain",
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    # If you're bumping build numbers manually, DELETE this block.
    increment_build_number(
      build_number: Time.now.to_i.to_s,
      xcodeproj: "Kuna.xcodeproj"
    )

    gym(
      scheme: "Kuna",
      project: "Kuna.xcodeproj",
      clean: true,
      output_directory: "fastlane/build",
      output_name: "Kuna.ipa",
      export_method: "app-store",
      include_symbols: true,
      xcargs: "-allowProvisioningUpdates"
    )
  end

  lane :upload_testflight do
