name: release-pr
on:
  push:
    branches: [ main ]     # runs when merges land on main
  workflow_dispatch: {}     # optional: run it by hand too

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-pr
  cancel-in-progress: false

jobs:
  release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Use a PAT if you want other workflows to run on the PR.
          # Otherwise the default GITHUB_TOKEN is fine but won't trigger follow-up CI.
          # token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-github-release: false
